apiVersion: v1
kind: Pod
metadata:
  name: my-app
status:
  conditions:
    - type: Available
      status: "True"

apiVersion: v1
kind: Service
metadata:
  name: my-app-service
status:
  loadBalancer: {}
