name: CI Setup for Building Image, Deploying App, and Testing

on:
  push:
    branches:
      - '*'  # Trigger the workflow on every push to any branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx (for building images)
        uses: docker/setup-buildx-action@v2  # Updated version

      # Set up KIND (alternative manual setup)
      - name: Set up KIND
        run: |
          curl -Lo kind https://github.com/kubernetes-sigs/kind/releases/download/v0.17.0/kind-linux-amd64
          chmod +x kind
          sudo mv kind /usr/local/bin/

      # Generate a unique image tag based on the commit SHA
      - name: Set Image Tag
        id: img_tag
        run: |
          IMAGE_TAG=$(echo $GITHUB_SHA | head -c 8)  # First 8 characters of the commit SHA
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t my-app:${{ env.IMAGE_TAG }} .

      - name: Create KIND Cluster
        run: |
          kind create cluster --name test-cluster --wait 5m

      - name: Load Docker Image into KIND
        run: |
          kind load docker-image my-app:${{ env.IMAGE_TAG }} --name test-cluster

      - name: Deploy to KIND cluster
        run: |
          kubectl apply -f k8s_resources/deployment.yaml
          kubectl apply -f k8s_resources/service.yaml

      - name: Install Conftest
        run: |
          curl -LO https://github.com/open-policy-agent/conftest/releases/download/v0.30.0/conftest_0.30.0_Linux_x86_64.tar.gz
          tar -xvf conftest_0.30.0_Linux_x86_64.tar.gz
          sudo mv conftest /usr/local/bin/

      # Verify deployment is running
      - name: Check deployment status
        run: |
          kubectl rollout status deployment/my-app --timeout=5m
          kubectl get pods

      # Test if the service is accessible by port-forwarding
      - name: Port forward and test service
        run: |
          kubectl port-forward service/my-app-service 8080:80 & # Forward port 8080 on localhost to port 80 on the service
          sleep 5  # Wait for port-forward to stabilize
          curl --max-time 10 http://localhost:8080  # Make an HTTP request to test if the service is accessible
        continue-on-error: true
      # Install Checkov
      - name: Install Checkov
        run: |
          pip install checkov

      # Run Checkov on Kubernetes files to check for security and compliance
      - name: Run Checkov on Kubernetes YAML files
        run: |
          checkov -d ./k8s_resources -o json > checkov-results.json

      # Upload Checkov results to GitHub Actions
      - name: Upload Checkov Results
        uses: actions/upload-artifact@v2
        with:
          name: checkov-results
          path: checkov-results.json

      - name: Run Conftest
        run: |
          conftest test ./k8s_resources/deployment.yaml --policy ./policies/example.rego

      - name: Install Trivy (Image Scanning Tool)
        run: |
          curl -sfL https://github.com/aquasecurity/trivy/releases/download/v0.61.0/trivy_0.35.0_Linux-x86_64.tar.gz -o trivy.tar.gz
          tar -xvzf trivy.tar.gz
          sudo mv trivy /usr/local/bin/

      - name: Scan Docker Image with Trivy
        run: |
          trivy image my-app:${{ env.IMAGE_TAG }}

      - name: Clean up KIND Cluster
        run: |
          kind delete cluster --name test-cluster
